- out_channels: 16
  stride: 1
- out_channels: 24
  stride: 1
- out_channels: 24
  stride: 1
- out_channels: 32
  stride: 2
- out_channels: 32
  stride: 1
- out_channels: 32
  stride: 1
- out_channels: 64
  stride: 2
- out_channels: 64
  stride: 1
- out_channels: 64
  stride: 1
- out_channels: 64
  stride: 1
- out_channels: 96
  stride: 1
- out_channels: 96
  stride: 1
- out_channels: 96
  stride: 1
- out_channels: 160
  stride: 2
- out_channels: 160
  stride: 1
- out_channels: 160
  stride: 1
- out_channels: 320
  stride: 1